name: tugas10
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  get_storage: ^2.1.1
  crypto: ^3.0.1
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.0.8
  uuid: ^3.0.7
  image_picker: ^1.0.7
  cached_network_image: ^3.2.1
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
